name: aspis
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.11.1
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: WantedSans
      fonts:
        - asset: fonts/WantedSans-Black.ttf
          weight: 900
        - asset: fonts/WantedSans-ExtraBlack.ttf
          weight: 800
        - asset: fonts/WantedSans-ExtraBold.ttf
          weight: 700
        - asset: fonts/WantedSans-Bold.ttf
          weight: 600
        - asset: fonts/WantedSans-SemiBold.ttf
          weight: 500
        - asset: fonts/WantedSans-Medium.ttf
          weight: 400
        - asset: fonts/WantedSans-Regular.ttf
          weight: 300